name: 'daily-github-summary'
description: 'Fetch GitHub metrics, render summary image, and publish to X/Twitter'

inputs:
  config_path:
    required: false
    default: 'config/default.yml'

  github_token:
    required: true
  x_consumer_key:
    required: true
  x_consumer_secret:
    required: true
  x_access_token:
    required: true
  x_access_secret:
    required: true

runs:
  using: 'composite'
  steps:
    - uses: oven/bun@v1
      with:
        bun-version: '1.x'

    - run: bun install
      shell: bash

    - name: Run summary
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        X_CONSUMER_KEY: ${{ inputs.x_consumer_key }}
        X_CONSUMER_SECRET: ${{ inputs.x_consumer_secret }}
        X_ACCESS_TOKEN: ${{ inputs.x_access_token }}
        X_ACCESS_SECRET: ${{ inputs.x_access_secret }}
      run: |
        bun run src/cli/main.ts --config "${{ inputs.config_path }}"
